# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self


pool: Default
variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'private registry'
        repository: 'unbound'
        #workingDirectory: '$(Build.SourcesDirectory)/src 
        buildContext: '$(Build.Repository.LocalPath)'
        dockerfile: '$(Build.SourcesDirectory)/Alpine/1.17.1/Dockerfile'
        tags: |
          latest